### PR TITLE
yes

### PR DESCRIPTION
**Pull request by xanthe1337**

### CODE REVIEW

**Comment by Fweak** [comment]
Hmm. Do i really want it tho ?

**Comment by xanthe1337** [comment]
yes dad

**Comment by Baecon** [comment]
lmao thats great, didnt know about that repo. i still wanna keep this version but ill include it in the readme.md if thats ok with you? ill even add your txt file as a seperate file

**Comment by Baecon** [comment]
if thats ok with you of course

**Comment by xanthe1337** [comment]
> lmao thats great, didnt know about that repo. i still wanna keep this version but ill include it in the readme.md if thats ok with you? ill even add your txt file as a seperate file

Much love, its ok u do you. I respect your love anyways! :D

**Comment by Jinxzyy** [comment]
he do be wanting it doe 😳

**Pull request closed without merging**
